# Generated by Django 3.2.9 on 2022-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_rename_salary_payment_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
