# Generated by Django 3.2.9 on 2022-07-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_payroll_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='Empid',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='test',
        ),
        migrations.AddField(
            model_name='payroll',
            name='Empid_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posApp.employee'),
        ),
    ]
