# Generated by Django 3.2.9 on 2022-07-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_auto_20220711_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='Empid_id',
            new_name='Empid',
        ),
    ]
