# Generated by Django 3.2.9 on 2022-07-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_rename_empid_id_payroll_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Date', models.DateField(blank=True, null=True)),
                ('To_Date', models.DateField(blank=True, null=True)),
                ('Paid_Date', models.DateField(blank=True, null=True)),
                ('Amount', models.FloatField(null=True)),
                ('Payment_Method', models.TextField(null=True)),
                ('Empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posApp.employee')),
            ],
        ),
    ]
