# Generated by Django 3.2.9 on 2022-07-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Remarks',
            field=models.TextField(null=True),
        ),
    ]
