# Generated by Django 3.2.9 on 2022-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_payments_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='Remarks',
            field=models.TextField(null=True),
        ),
    ]
